### ISSUE TITLE
FetchError: request to https://api.datadoghq.eu/api/v1/series failed

### ISSUE THREAD

**Issue by enric-joco** [dbader/node-datadog-metrics#114]
We have updated our service to node 20 and this error has incremented a lot, I have no idea what could be the problem.

FetchError: request to https://api.datadoghq.eu/api/v1/series failed, reason: 
    at ClientRequest.<anonymous> (/src/debeaconizer/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at req.emit (/src/debeaconizer/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:97:25)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:526:35)
    at TLSSocket.emit (/src/debeaconizer/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Mr0grog** [comment]
For what it’s worth, I’ve tried this on Node v20.8.0 against both the EU and US3 sites and am not seeing any issues. I think I’m going to need some more details on how to recreate the error to help address it.

**Comment by Mr0grog** [comment]
Alright, I’m going ahead and closing this since there hasn't been any more feedback or details.

Please feel free to post here again with more info if you are still experiencing the problem and I will re-open this.
