### ISSUE TITLE
Error: DATADOG_API_KEY environment variable not set

### ISSUE THREAD

**Issue by scholarj** [dbader/node-datadog-metrics#20]
Error: DATADOG_API_KEY environment variable not set
    at new DataDogReporter (/.../node_modules/datadog-metrics/lib/reporters.js:29:15)
    at new BufferedMetricsLogger (/.../node_modules/datadog-metrics/lib/loggers.js:40:38)
    at init (/.../node_modules/datadog-metrics/index.js:24:20)
    at callOnSharedLogger (/.../node_modules/datadog-metrics/index.js:31:9)
    at Object.increment (/.../local_modules/lib/datadog.js:64:70)
    at ServerResponse.res.end (/.../local_modules/middleware-app/app-metrics.js:49:13)
    at ServerResponse.send (/.../node_modules/express/lib/response.js:205:10)
    at ServerResponse.res.send (/.../local_modules/middleware-app/app-metrics.js:29:10)
    at ServerResponse.json (/.../node_modules/express/lib/response.js:250:15)
    at ServerResponse.send (/.../node_modules/express/lib/response.js:152:21)
    at ServerResponse.res.send (/.../local_modules/middleware-app/app-metrics.js:29:10)
    at /.../local_modules/middleware-app/respond-or-404.js:22:9
    at Layer.handle [as handle_request] (/.../node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/.../node_modules/express/lib/router/index.js:312:13)
    at /.../node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/.../node_modules/express/lib/router/index.js:330:12)
    at next (/.../node_modules/express/lib/router/index.js:271:10)
    at Layer.handle [as handle_request] (/.../node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/.../node_modules/express/lib/router/index.js:312:13)
    at /.../node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/.../node_modules/express/lib/router/index.js:330:12)
    at Immediate.next (/.../node_modules/express/lib/router/index.js:271:10)

My init logic is such:
 49         _instance = new ddMetrics.BufferedMetricsLogger({
 50           apiKey: APIKEY,
 51           host: HOSTNAME,
 52           prefix: PREFIX,
 53           flushIntervalSeconds: INTERVAL
 54         })

All cap-variables come in via a configuration system we use.

My understanding from your docs is that if I pass in the API KEY this way it's optional to have it as an env var but on every pageview (call to your .increment()) I get this stacktrace. In production we can't have "extra" env vars.

Please advise.

And thank you for your work on this module! :-)

**Comment by scholarj** [comment]
Found the issue - was in my code not yours!!! (calling the wrong instance) Please close this and sorry for the hassle.

**Comment by dbader** [comment]
No worries! Closing now.
